### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by zp19990818** [Junhua-Liao/Light-ASD#1]
学长好！

请问方便提供一份少量的预处理完的测试数据集吗？🌹

**Comment by Junhua-Liao** [comment]
您好，数据集比较庞大并不方便上传。但是您可以根据以下代码轻松获得预处理后的数据集：
python train.py --dataPathAVA AVADataPath --download 
您可以对utils文件夹下的tools.py中的部分代码进行修改，以此仅获得预处理后的测试集。

**Comment by zp19990818** [comment]
> 

感谢学长回复！可是运行下载和预处理数据的命令时，会显示权限不足无法读取。我自己去网上查了下，把文件夹的权限改成了完全控制，但是还是报这个错误。我的运行环境是win10，能麻烦学长看一下吗？
![image](https://user-images.githubusercontent.com/53686038/226282366-1df8569d-68ed-4104-b01b-e3a291b48428.png)

**Comment by Junhua-Liao** [comment]
我估计可能是csv.tar.gz并未下载成功，从而导致拒绝访问。你检查一下AVADataPath里是否有下载的csv.tar.gz文件呢。

**Comment by Junhua-Liao** [comment]
如果代码自动下载csv.tar.gz失败，你可以尝试访问以下网站直接手动下载:
https://drive.google.com/uc?id=1C1cGxPHaJAl1NQ2i7IhRgWmdvsPhBCUy

**Comment by zp19990818** [comment]
> 如果代码自动下载csv.tar.gz失败，你可以尝试访问以下网站直接手动下载: https://drive.google.com/uc?id=1C1cGxPHaJAl1NQ2i7IhRgWmdvsPhBCUy

好的，谢谢啦~

**Comment by Junhua-Liao** [comment]
小事，希望这能帮助到你，祝你科研顺利！

**Comment by Junhua-Liao** [comment]
你好，我发现这个仓库将预处理后的AVA验证集上传至了百度网盘。
https://github.com/huangmin9966/FSDNet_RealTimeArch
我在该数据集上进行了验证，并取得了相同的结果。希望能帮助到你。

**Comment by zp19990818** [comment]
> 你好，我发现这个仓库将预处理后的AVA验证集上传至了百度网盘。 https://github.com/huangmin9966/FSDNet_RealTimeArch 我在该数据集上进行了验证，并取得了相同的结果。希望能帮助到你。

收到！感谢
