### ISSUE TITLE
Demo with Visualization

### ISSUE THREAD

**Issue by mvoodarla** [Junhua-Liao/Light-ASD#10]
Hey folks - I really love this model so I made a demo and put it up here! Feel free to try it for yourself. Also made a few changes that makes the implementation slightly faster and work better through scene cuts.

https://www.sievedata.com/functions/sieve/light-asd

P.S. I work at this company [Sieve](https://sievedata.com/) that works on video and audio AI.

**Comment by Junhua-Liao** [comment]
Thank you for your contributions. I believe it will be valuable for future research.

**Comment by mujavidb** [comment]
@mvoodarla This is a great example, and very helpful to see. I noticed some of Sieve's other works are also public repos. Are there plans to make your implementation of LightASD publicly visible?

**Comment by mvoodarla** [comment]
Hey! Apologies for the late reply. We hope to soon!
