### ISSUE TITLE
Implementation difference compared to TalkNet-ASD

### ISSUE THREAD

**Issue by radioactive11** [Junhua-Liao/Light-ASD#12]
Hello

I was measuring the performance difference between [TalkNet-ASD](https://github.com/TaoRuijie/TalkNet-ASD) and Light-ASD and discovered most of the implementation is similar. Can someone point out the major differences which lead to a performance boost?

Thank You 🙌🏽

**Comment by Junhua-Liao** [comment]
Thank you for your interest in our work. 
Light-ASD modifies on the open source code of TalkNet, so the code is consistent in terms of data loading, testing performance, and so on. The differences in performance primarily stem from variances in network architecture.

**Comment by radioactive11** [comment]
@Junhua-Liao Thank you the clarification ✌🏽
