### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by charlotteburkirts** [Junhua-Liao/Light-ASD#13]
Hello and thanks for sharing your work.

I would like to train on a different dataset but your training relies on the train_loader.csv which is a transformation of the train_orig.csv. But the transformation is not documented anywhere.
From what I can guess:

  header1: instance_id
  header2: number of frames on which the face appear
  header3: ?
  header4: list of boolean representing speaking not speaking on each frame
  header5 ?
  
  Could you give a bit more documentation about this csv? Maybe the code to generate it ?

**Comment by charlotteburkirts** [comment]
All good, found the information here:
https://github.com/TaoRuijie/TalkNet-ASD/issues/10
I'm closing the issue.

**Comment by Vikramank** [comment]
Hi @charlotteburkirts ,
Were you able to train TalkNet to your custom model?
