### ISSUE TITLE
Hi, do you have any inference code?

### ISSUE THREAD

**Issue by furqan4545** [Junhua-Liao/Light-ASD#15]
Hi, great work.  Do you have any inference code to test it out quickly? I would highly appreciat, thanks

**Comment by VirajDeshwal** [comment]
Use this to run the inference - ` python Columbia_test.py --videoName <video name>  --videoFolder demo --pretrainModel weight/finetuning_TalkSet.model

**Comment by furqan4545** [comment]
<img width="1082" alt="image" src="https://github.com/Junhua-Liao/Light-ASD/assets/50285664/9786a700-9de0-4a2c-b1c0-664d23b3995b">

I am getting this error..

**Comment by furqan4545** [comment]
<img width="1066" alt="image" src="https://github.com/Junhua-Liao/Light-ASD/assets/50285664/11f363ca-d167-4068-93f3-7ebb90776e6a">

Thanks for the reply man. I got new errors now. I wonder if we can sync up and update the code so people can use inference easily.

**Comment by furqan4545** [comment]
sorry it was basic error.. I resolved.

**Comment by VirajDeshwal** [comment]
@Junhua-Liao This issue is resolved. Kindly please close it.
