### ISSUE TITLE
仅使用视频输入进行检测的性能

### ISSUE THREAD

**Issue by Page-Jiao** [Junhua-Liao/Light-ASD#16]
非常感谢您的工作；能否请问一下您有没有测试过在只利用视频输入的情况下，模型的检测性能；因为有一些唇语识别的场景下，音频通常是无法获取的。

**Comment by Junhua-Liao** [comment]
感谢您对我们的工作感兴趣。您可以尝试修改代码以满足唇语识别任务的需求，比如将Visual Feature Encoder提取的视觉特征直接送到Classifier进行时序建模和预测。
