### ISSUE TITLE
Couldn't be able to reproduce the reported validation result after training

### ISSUE THREAD

**Issue by Falmi** [Junhua-Liao/Light-ASD#17]
Thanks for the contribution and for sharing. 

I got the 93.34% after training the network for 30 epochs.
![image](https://github.com/Junhua-Liao/Light-ASD/assets/26068376/4e60bc35-8961-4a88-b758-005e1a96ad55)

During training the validation result didn't exceed 93.62 after training for 18 epochs.
![image](https://github.com/Junhua-Liao/Light-ASD/assets/26068376/7dea7ab7-b18a-471e-955d-b6f46a8abcd4)

I would appreciate it if you could provide a clue on how to reproduce the validation result reported on the paper. Thanks

**Comment by Junhua-Liao** [comment]
The training of the model can be affected by hardware and software versions. You can refer to the software versions mentioned in issue #5 or directly use the model weights we provide.

**Comment by Falmi** [comment]
Thanks, I'll try it.
