### ISSUE TITLE
Using Cropped Faces

### ISSUE THREAD

**Issue by lix4** [Junhua-Liao/Light-ASD#18]
Hello! Thank you for posting the code for this nice work. I have one question: Why do people use cropped faces as input instead of original images as input and turn detection task to a off-shelf detection model? I assume they want to make the model focus more on classification and don't let the model ruin the detection results. Is it correct? Thank you!

**Comment by Junhua-Liao** [comment]
Thank you for your interest in our work. The active speaker detection task is a specific instance of audio-visual separation. If you want to detect the speaker from the original video, you can focus on the related work of speaker diarization [1].
﻿
[1] Xu, Eric Zhongcong, et al. "Ava-avd: Audio-visual speaker diarization in the wild." Proceedings of the 30th ACM International Conference on Multimedia. 2022.
