### ISSUE TITLE
Reproducing the result on the  Columbia dataset

### ISSUE THREAD

**Issue by Falmi** [Junhua-Liao/Light-ASD#21]
This is the result I got on Columbia dataset which is not the same with the one you have reported in the paper. Could you help on how to reproduce the result you have reported in your paper. Thanks
![image](https://github.com/user-attachments/assets/9e97dd98-d43c-481f-a35d-1a0d8f7e8459)

**Comment by Junhua-Liao** [comment]
It may be an issue with the software package version. (numpy = 1.21.2 and ffmpeg-3.1)
![IMG_0263](https://github.com/user-attachments/assets/db72468f-690f-4649-865e-9070a16acbc7)

**Comment by SebastianJanampa** [comment]
Hi,
I am facing the same problems. I can reproduce the results for the AVA dataset, but not for the Columbia dataset. @Junhua-Liao could you provide a requirement.txt file with the libraries and their versions for this project?

@Falmi could you solve this problem?
