### ISSUE TITLE
No such file sfd_face.pth

### ISSUE THREAD

**Issue by yangshuer** [Junhua-Liao/Light-ASD#22]
Hello, I found that the required files are missing while testing this project. Error message:
FileNotFoundError: [Errno 2] No such file or directory: '~/WorkFolder/video_check/models/Light-ASD/model/faceDetector/s3fd/sfd_face.pth'

**Comment by Junhua-Liao** [comment]
Thanks for your interest in our work. This issue can be referred to #19.
