### ISSUE TITLE
关于模型针对嘴唇动作视频问题

### ISSUE THREAD

**Issue by 821029883** [Junhua-Liao/Light-ASD#23]
作者您好，感谢您出色的开源结果。
我在使用不同测试视频时，出现以下问题。

1. 如果视频中，人物嘴唇不动作，但是背景存在人声，这种情况下score得分会很低(满足预期不同步)
![image](https://github.com/user-attachments/assets/f3de666d-e008-4393-8630-ed4686beb212)
2. 如果视频中，人物嘴唇动作，背景也存在人声(这里我使用了A的嘴唇动作视频，B的人声合成成为了一个视频，A和B说话的内容不想干)，模型推理结果得分的score却比较高。(不符合预期)
![image](https://github.com/user-attachments/assets/ca304bb1-285b-42fe-a3f0-0c413e06a751)

正常来讲2这种情况，应当也判定为不同步的，但是貌似模型只要有嘴唇动作，就会有一个比较高的分数，这是模型的问题吗

**Comment by 821029883** [comment]
1. 以下是Light-ASD结果
https://github.com/user-attachments/assets/7e1bb2aa-5146-4c2a-95be-f0a7158be3ad
2. 以下是TalkNet-ASD结果
https://github.com/user-attachments/assets/88623e26-e591-425b-881f-ee05dfd3323f
可以观察到Light-ASD基本只有嘴唇有动作，score基本都会>0，TalkNet-ASD则相对比较符合预期

**Comment by Junhua-Liao** [comment]
感谢您对我们的工作感兴趣。
在这项研究中，我们主要关注一般场景下的主动说话人检测，并未针对一些特殊场景进行特定设计。
在后续的研究中，我们也发现模型在屏幕中的人存在嘴唇运动且有屏幕外的人声时，容易误检。
这可能是一个值得深入研究的问题。

**Comment by pwtm2** [comment]
你好，我也非常赞同大家对您工作的赞美——真的做得非常棒。

我遇到了类似的情况——当我录制一个仅有嘴唇动作但没有发声的视频时，得分依然很高。

我原以为即使是一个简单的语音活动检测器（VAD）结合得分，也会更稳健一些；但理想情况下，得分应该基于同步的语音和嘴唇动作吧？我很好奇我们可以如何进一步探索这一点。

再次感谢您出色的工作！

Hi there, I second the praise for the work - really well done.

I am experiencing the same - I get high scores when I record a video of myself moving my lips but not talking.

I would have thought even a simple VAD combined with the score would be slightly more robust; but ideally the score would be based on synchronous speech and lip movement? I wonder how we could explore this further.

Thanks again for the great work!

**Comment by Junhua-Liao** [comment]
感谢您对我们的工作感兴趣
造成该现象的原因可能有两点：
（1）模型参数量较少，限制了其应对这种特殊场景的能力
（2）AVA数据集中针对这种特殊场景的数据可能较少
最新的开源数据集WASD [1] 中包含了人声噪音和语音重叠这两种特殊情况，该作者也使用Light-ASD进行了实验。后续有研究[2]基于WASD数据集改进了Light-ASD。
希望这些能够对您的研究有所帮助。

[1] Roxo, Tiago, et al. "WASD: A Wilder Active Speaker Detection Dataset." IEEE Transactions on Biometrics, Behavior, and Identity Science (2024).
[2] Carneiro, Hugo, and Stefan Wermter. "FabuLight-ASD: Unveiling Speech Activity via Body Language." arXiv preprint arXiv:2411.13674 (2024).

**Comment by 821029883** [comment]
感谢您的耐心解答，我将尝试下使用其他数据集训练的模型，再表感谢
