### ISSUE TITLE
Can the frame rate of the video change?

### ISSUE THREAD

**Issue by liuruoling** [Junhua-Liao/Light-ASD#24]
Hello,I've noticed that the video preprocessing time is too long. Test results show that face detection takes up half of the total running time, yet the processing time for a single frame of face detection is obviously quite fast. Therefore, my idea is to increase speed by reducing the frame rate and the number of frames, but the recognition results are not good.

My questions are: Does the model support frame rates other than 25FPS? Why does reducing the frame rate degrade the recognition effect? Are there other ways to improve speed?

**Comment by Junhua-Liao** [comment]
Thank you for your interest in our work.
This work has not been specifically designed to address the case of reduced frame rates. 
The decrease in frame rate may have impacted the model's ability to extract lip-change information, leading to a mismatch with the audio data. 
The data preprocessing method used in this work follows the approach of TalkNet and ADENet. Replacing the face recognition algorithm with a faster one and optimizing the extraction of face sequences could enhance processing speed.

**Comment by liuruoling** [comment]
Thank you for your answer.This is of great help to me.
After multiple tests, I found that the model performs very well under normal circumstances. However, in certain situations, its recognition performance is not good.
![video_out avi_20241211_144216 951](https://github.com/user-attachments/assets/20024046-58c0-4fb6-b634-0ca63b31d826)
![video_out avi_20241211_151716 202](https://github.com/user-attachments/assets/3b17d286-421f-41ee-b1f1-bc5b9a796d21)

I've found that when the face size is relatively small, the face detection model fails to recognize faces. However, when I lower the threshold for face detection, the performance of the face detection model improves. 
But the recognition effect of the model is still not good, as shown in the above figure, where a face is detected and it is obvious that the person is speaking, but the score is negative, indicating that the current face is not speaking.
I would like to ask if the model has any specific requirements or limitations, such as requirements for video quality or face size? Sometimes the model performs poorly, could it be due to these factors?

**Comment by Junhua-Liao** [comment]
Indeed, as shown in Figure 6b of the paper, the prediction performance of all methods decreases for small-sized faces. The latest open-source dataset WASD[1] focuses on some special cases, which may be helpful for your research.

[1] Roxo, Tiago, et al. "WASD: A Wilder Active Speaker Detection Dataset." IEEE Transactions on Biometrics, Behavior, and Identity Science (2024).

**Comment by liuruoling** [comment]
Thank you for your patience. Your detailed explanations have been very helpful to me.
