### ISSUE TITLE
Preprocessing takes too much time

### ISSUE THREAD

**Issue by jun297** [Junhua-Liao/Light-ASD#4]
Hi, thank you for sharing code. It is a nice work.

I want to evaluate Light-ASD on in-the-wild YouTube video.

While Light-ASD is fast and accurate, for me, preprocessing (extracting video frame, face detection, face crop) is too slow.
Is there a good way to reduce the time?

Thank you

**Comment by Junhua-Liao** [comment]
Hello, thank you for your interest in our work.

As the AVA dataset consists of facial sequences and the corresponding audio, Light-ASD did not specifically optimize the data preprocessing component. We adopted the preprocessing approach used by [TalkNet](https://github.com/TaoRuijie/TalkNet-ASD) to extract face tracking of speakers from the raw videos using S3FD, and validated it on the Columbia dataset. You can place the raw video (`name.mp4` and `name.avi` are both fine) in a folder named `folder` and run the following code for detection.

`python Columbia_test.py --videoName name --videoFolder folder`

 Perhaps you can achieve faster processing by replacing S3FD with a more efficient method in the `Columbia_test.py` file.

**Comment by jun297** [comment]
Although replacing S3FD is one of the possible solutions, replacing ffmpeg preprocessing seems to be tough.

Thank you for the reply.

**Comment by jun297** [comment]
Although replacing S3FD is one of the possible solutions, replacing ffmpeg preprocessing seems to be tough.

Thank you for the reply.

**Comment by andrea-gatto** [comment]
Concerning speeding up the extraction of video frames, I wonder if extracting and working on every n frames instead of all of them would make the performance much worse

**Comment by jun297** [comment]
@andrea-gatto I don't think that there would be a performance degradation
using ffmpeg less can be a detour
I'm trying to hardware accel
https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html

**Comment by andrea-gatto** [comment]
@jun297 I tried running ffmpeg on frames extraction on one A10G GPU, I don't really see a speed-up unfortunately

**Comment by jun297** [comment]
@andrea-gatto Is there no difference despite the hardware accel?
I'm sorry but I haven't tried yet. I am considering extract frames with denseflow or opencv
you can refer:
https://github.com/open-mmlab/mmaction/blob/master/DATASET.md#extract-frames
https://github.com/open-mmlab/denseflow

**Comment by andrea-gatto** [comment]
Yeah no difference at all, the GPU is running at 1% and I get the same time as on CPU, I cannot exclude that switching to a different GPU would give the same result
Agreed probably the way to go is to move to something else like the stuff you linked
