### ISSUE TITLE
咨询视觉块

### ISSUE THREAD

**Issue by attutude** [Junhua-Liao/Light-ASD#8]
你好，感谢你出色的工作，我学习了你发布的视觉块代码，代码使用的是3D卷积，而不是像论文描述的，将3D卷积分解为2D卷积和1D卷积来分别提取候选人脸序列的空间和时间信息。感谢你能回答我的问题
![image](https://github.com/Junhua-Liao/Light-ASD/assets/62997406/a69852df-b68d-4e8d-aa03-e89fa3c68eca)

**Comment by Junhua-Liao** [comment]
你好，感谢你对我们的工作感兴趣。
在提取空间特征时，时间维度的卷积核大小为1，此时3D卷积等价为2D卷积。提取时间特征时同理。
如果使用nn.Conv2D和nn.Conv1D，则每次卷积操作前都需要reshape特征块，以满足2D和1D卷积的输入维度要求，这样会大幅增加计算成本。

**Comment by attutude** [comment]
> 你好，感谢你对我们的工作感兴趣。 在提取空间特征时，时间维度的卷积核大小为1，此时3D卷积等价为2D卷积。提取时间特征时同理。 如果使用nn.Conv2D和nn.Conv1D，则每次卷积操作前都需要reshape特征块，以满足2D和1D卷积的输入维度要求，这样会大幅增加计算成本。

谢谢，我明白了
![33ZP(L0_BU5T9%IEMWO_`OE](https://github.com/Junhua-Liao/Light-ASD/assets/62997406/3cc2f67e-c0cd-4dac-a45c-74eee055f89e)
